### ISSUE TITLE
Structured data about workshop

### ISSUE THREAD

**Issue by SvenLieber** [kg-construct/workshop#11]
Hi,

do you publish (or internally maintain) structured data and third-party identifiers about the workshop or related entities such as presentations, participants etc?

In the past I curated data about the workshop on Wikidata: for example the workshop series [Q117087609](https://www.wikidata.org/wiki/Q117087609) and the 2022 edition [Q113576121](https://www.wikidata.org/wiki/Q113576121).

Especially adding all members of the program committee takes time as I have to manually look up the persons on Wikidata to add a link. In case you use an automated tool to generate the website based on CSV data, I thought it might be more efficient to enrich the internal CSV list with external identifiers (such as Wikidata).

It does not have to be Wikidata. In general I think it would be good practice to add the [ORCID ](https://orcid.org/) identifier of persons and the [ROR ](https://ror.org/) identifier of their organizations. This would not only integrate the workshop better to other datasets, but would also contribute to a better visibility of the workshop contributors in terms of Open Science.

By using some icons this could look like in the following example of [Open Source proceedings](https://www.tib-op.org/ojs/index.php/CoRDI/article/view/381):

![image](https://github.com/kg-construct/workshop/assets/3501171/d6af9441-25ad-4859-9934-b6f172f7964b)

Let me know what you think. In case this requires a bit of development or data curation I can definitely help.

Sven

**Comment by dachafra** [comment]
Hi @SvenLieber,
Sorry for the late reply! We started in the first editions of the workshop (first and second), to generate the website automatically based on a KG constructed from CSV data and RML mappings. As the website didn't change a lot (PC members were mostly the same, OC is the same, etc etc) for the last editions we just copy-paste the previous version of the website and updated it, so there is no structured data at this moment :-(
