### ISSUE TITLE
Setup OpenReview for submissions

### ISSUE THREAD

**Issue by dachafra** [kg-construct/workshop#2]

**Comment by pheyvaer** [comment]
Requested. Waiting for approval from OpenReview.

**Comment by pheyvaer** [comment]
@dachafra Approved! https://openreview.net/group?id=kg-construct.github.io/KGCW/2022/Workshop
Can you have a look if everything is ok? Normally, you also should have access to the PC console.

**Comment by dachafra** [comment]
looks great! thanks :-)
