### ISSUE TITLE
Generate a video script

### ISSUE THREAD

**Issue by dachafra** [kg-construct/workshop#4]

**Comment by pheyvaer** [comment]
@dachafra Could you give me the requirements of the script? Thanks!

**Comment by dachafra** [comment]
From ESWC, they mention in the call for workshops that the video should be about 1 min. No more requirements

**Comment by pheyvaer** [comment]
Ok, but you mentioned some ideas already no? Could you share them again? 😄

**Comment by dachafra** [comment]
"The main idea would be to show a “crazy” guy with many mapping rules specs, ontologies, data, etc with the final message that we need to automatize somehow the process and asking for help to other researchers"

**Comment by pheyvaer** [comment]
Setting:

- Desk with computer and stacks of papers
- Whiteboard/blackboard with post-its and text

Text:
- Talking to him/herself while working computer, writing things down, looking at whiteboard/blackboard.
    - What data do I need?
    - Do I need this database or this file?
    - Well, it depends what ontology I will use.
    - Or should a vocabulary be enough?
    - Aah, but didn’t my boss give me a shape?
    - But not sure if that one is complete actually and even up to date with the newest ontologies?
    - Ok, let’s take this data and go with these 2 ontologies. Should work fine as a first version.
    - Aah shoot, what mapping language should I use now? We don’t have our machines yet, so not your what languages we can actually execute.
    - Pffff, I give up. Too many variables here!!

Add the end, we get a simple message on a black screen: "Like many others in this world, this person could use your help. Submit your paper about the automation of knowledge graph construction now."

@dachafra What do you think?

**Comment by dachafra** [comment]
looks good! I'll try to record it today!
